<?php

class Mail extends \ProcessWire\Process
{
    public static function getModuleinfo()
    {
        return [
            'title' => 'Mail',
            'summary' => '',
            'author' => '',
            'version' => 1,
            'icon' => 'cubes'
        ];
    }

    public function send($subject='Test',$emails=['test@gmail'],$content='Test')
    {
        $transport = (new Swift_SmtpTransport('smtp.gmail.com', 587,'tls'))
            ->setUsername('test')
            ->setPassword('test');

        $mailer = new Swift_Mailer($transport);

        $message = (new Swift_Message($subject))
            ->setFrom(['test' => 'Universal '.$subject])
            ->setTo($emails)
            ->setBody($content)
            ->setContentType("text/html");


        try {
            $result = $mailer->send($message);
        }
        catch (Exception $e)
        {
            $result = $e;
        }
        return $result;
    }
}





